const F={id:'SOP ID',title:'SOP TITLE',model:'MODEL',version:'VERSION',client:'CLIENT ID',status:'STATUS',current:'CURRENT PAGE',total:'TOTAL PAGES',data:'SOP DATA',assets:'SOP ASSETS',excel:'SOP EXCEL',createdAt:'CREATED AT',updatedAt:'UPDATED AT',createdBy:'CREATED BY',updatedBy:'UPDATED BY',note:'NOTE'};
const REQUIRED=Object.values(F);
export class SopError extends Error{constructor(code,message,status=400){super(message);this.name='SopError';this.code=code;this.status=status;}}
const text=value=>Array.isArray(value)?value.map(v=>v?.text||'').join(''):String(value??'');
const copy=value=>structuredClone(value);
const pageId=()=>`page-${crypto.randomUUID()}`;
export function torontoDate(now=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now),get=t=>parts.find(p=>p.type===t).value;return `${get('year')}${get('month')}${get('day')}`;}
export function blankPage(project={}){return {pageId:pageId(),zone2:{stationName:'',nextStationName:'',toolsEquipmentSupplies:'',standardTimeSeconds:0},zone3:{layout:'two-images',image1:null,image2:null,image3:null,caption1:'',caption2:'',caption3:'',annotations:{image1:[],image2:[],image3:[]}},zone4:{text:''},zone5:{text:''},zone6:{safetyIcons:[]},zone7:{approvedBy:'',approvedDate:'',reviewedBy:'',reviewedDate:'',auditedBy:'',auditedDate:'',preparedBy:project.preparedBy||'',preparedDate:project.preparedDate||''}};}
export function initialData(input,sopId){const project={clientId:text(input.clientId).trim(),model:text(input.model).trim(),version:text(input.version).trim(),zone1:{documentNumber:sopId,materials:Array.isArray(input.materials)?input.materials.map(row=>({name:text(row.name).trim(),partNumber:text(row.partNumber).trim(),quantity:text(row.quantity).trim()})):[]},preparedBy:text(input.preparedBy).trim(),preparedDate:text(input.preparedDate).trim()};return {schemaVersion:1,sopId,title:text(input.title).trim()||'作业指导书',status:'Draft',project,pages:[blankPage(project)],currentPage:1};}
function validate(data){if(!data||typeof data!=='object'||Array.isArray(data))throw new SopError('MALFORMED_SOP_DATA','Saved SOP data is invalid.',422);if(data.schemaVersion!==1)throw new SopError('UNSUPPORTED_SOP_SCHEMA','This SOP version is not supported.',422);if(!Array.isArray(data.pages)||!data.pages.length)throw new SopError('MALFORMED_SOP_DATA','Saved SOP must contain at least one page.',422);return data;}
function parse(record){let data;try{data=JSON.parse(text(record.fields?.[F.data]));}catch{throw new SopError('MALFORMED_SOP_DATA','Saved SOP data is invalid.',422);}return validate(data);}
function publicData(data){const result=copy(data);for(const page of result.pages)for(const key of ['image1','image2','image3'])if(page.zone3?.[key]){delete page.zone3[key].fileToken;page.zone3[key].url=`/api/sops/${encodeURIComponent(result.sopId)}/assets/${encodeURIComponent(page.zone3[key].assetId)}`;}return result;}
function attachmentMap(record){const result=new Map();for(const file of Array.isArray(record.fields?.[F.assets])?record.fields[F.assets]:[])if(file?.name&&file?.file_token)result.set(text(file.name),text(file.file_token));return result;}
function summary(record){const f=record.fields||{};return {recordId:record.record_id,sopId:text(f[F.id]),title:text(f[F.title]),model:text(f[F.model]),clientId:text(f[F.client]),status:text(f[F.status]),totalPages:Number(f[F.total]||0),updatedAt:f[F.updatedAt]||null,updatedBy:text(f[F.updatedBy])};}
export function createSopService(config,records,attachments,options={}){
 const now=options.now||(()=>new Date()),uuid=options.uuid||(()=>crypto.randomUUID());
 const args=()=>{if(!config.sopTableId)throw new SopError('SOP_NOT_CONFIGURED','SOP CLASS table is not configured.',503);return {appToken:config.appToken,tableId:config.sopTableId};};
 async function schema(){const fields=await records.listFields(args()),names=new Set(fields.map(f=>f.field_name)),missing=REQUIRED.filter(name=>!names.has(name));if(missing.length)throw new SopError('SOP_SCHEMA_ERROR','SOP CLASS schema is incomplete.',503);return fields;}
 async function rows(){await schema();return records.listRecords(args());}
 async function allocate(){const day=torontoDate(now()),prefix=`MKS-${day}-SOP-`,used=new Set((await rows()).map(r=>text(r.fields?.[F.id])));let n=1,id;do{id=prefix+String(n++).padStart(3,'0');}while(used.has(id));return id;}
 async function find(sopId){const matches=(await rows()).filter(r=>text(r.fields?.[F.id])===sopId);if(matches.length!==1)throw new SopError(matches.length?'DUPLICATE_SOP_ID':'SOP_NOT_FOUND',matches.length?'SOP ID is duplicated.':'SOP was not found.',matches.length?409:404);return matches[0];}
 async function create(input){const sopId=await allocate(),data=initialData(input,sopId),stamp=now().getTime(),actor=text(input.updatedBy||input.createdBy).trim(),fields={[F.id]:sopId,[F.title]:data.title,[F.model]:data.project.model,[F.version]:data.project.version,[F.client]:data.project.clientId,[F.status]:'Draft',[F.current]:1,[F.total]:1,[F.data]:JSON.stringify(data),[F.createdAt]:stamp,[F.updatedAt]:stamp,[F.createdBy]:actor,[F.updatedBy]:actor,[F.note]:text(input.note).trim()};const saved=await records.createRecord({...args(),fields});return {...summary(saved),sopData:publicData(data)};}
 async function list({query='',status='',clientId=''}={}){const q=text(query).trim().toLowerCase();return {sops:(await rows()).map(summary).filter(s=>(status?s.status===status:s.status!=='Archived')&&(!clientId||s.clientId===clientId)&&(!q||`${s.sopId} ${s.title} ${s.model} ${s.clientId}`.toLowerCase().includes(q))).sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0))};}
 async function get(sopId){const record=await find(sopId),data=parse(record);data.currentPage=Math.min(Math.max(Number(record.fields?.[F.current]||data.currentPage||1),1),data.pages.length);return {...summary(record),sopData:publicData(data)};}
 async function hydrateAssets(incoming,current,record){const existing=new Map(),stored=attachmentMap(record),tokens=new Map();for(const page of current.pages)for(const key of ['image1','image2','image3']){const image=page.zone3?.[key];if(image?.assetId){const token=text(image.fileToken)||stored.get(text(image.fileName));if(token)existing.set(image.assetId,{image,token});}}for(let p=0;p<incoming.pages.length;p++)for(const [index,key] of ['image1','image2','image3'].entries()){const image=incoming.pages[p].zone3?.[key];if(!image)continue;if(image.pendingImage){const raw=image.pendingImage;if(!['image/png','image/jpeg','image/webp'].includes(raw.type)||typeof raw.base64!=='string')throw new SopError('INVALID_SOP_IMAGE','Use a PNG, JPG, JPEG, or WEBP image.');const bytes=Uint8Array.from(atob(raw.base64),c=>c.charCodeAt(0));if(!bytes.length||bytes.length>10*1024*1024)throw new SopError('INVALID_SOP_IMAGE','SOP image must be between 1 byte and 10 MiB.');const ext=raw.type==='image/png'?'png':raw.type==='image/webp'?'webp':'jpg',fileName=`${incoming.sopId}-P${String(p+1).padStart(3,'0')}-IMG${index+1}.${ext}`,fileToken=await attachments.upload({appToken:config.appToken,fileName,bytes,mimeType:raw.type}),assetId=`asset-${uuid()}`;incoming.pages[p].zone3[key]={assetId,fileName,mimeType:raw.type,slot:index+1,fit:image.fit||'contain',position:image.position||{x:50,y:50}};tokens.set(assetId,fileToken);}else{const saved=existing.get(image.assetId);if(!saved)throw new SopError('UNKNOWN_SOP_ASSET','SOP image reference is invalid.',422);const metadata=copy(saved.image);delete metadata.fileToken;delete metadata.url;delete metadata.pendingImage;incoming.pages[p].zone3[key]=metadata;tokens.set(image.assetId,saved.token);}}return tokens;}
 async function update(sopId,input){const record=await find(sopId),current=parse(record),incoming=validate(copy(input.sopData));if(incoming.sopId!==sopId)throw new SopError('SOP_ID_MISMATCH','SOP identity cannot be changed.',409);const assetTokens=await hydrateAssets(incoming,current,record);incoming.currentPage=Math.min(Math.max(Number(incoming.currentPage||1),1),incoming.pages.length);const tokens=[...new Set(assetTokens.values())];const stamp=now().getTime(),fields={[F.title]:incoming.title,[F.model]:incoming.project.model,[F.version]:incoming.project.version,[F.client]:incoming.project.clientId,[F.status]:['Draft','Completed','Archived'].includes(incoming.status)?incoming.status:'Draft',[F.current]:incoming.currentPage,[F.total]:incoming.pages.length,[F.data]:JSON.stringify(incoming),[F.updatedAt]:stamp,[F.updatedBy]:text(input.updatedBy).trim(),[F.assets]:tokens.map(file_token=>({file_token}))};const saved=await records.updateRecord({...args(),recordId:record.record_id,fields}),complete={...record,...saved,fields:{...record.fields,...saved.fields}};return {...summary(complete),sopData:publicData(incoming)};}
 async function saveExcel(sopId,input){const record=await find(sopId),fileName=`${sopId}.xlsx`;if(text(input.fileName)!==fileName||typeof input.base64!=='string'||!input.base64.length)throw new SopError('INVALID_SOP_EXCEL','Generated SOP workbook is invalid.',400);let bytes;try{bytes=Uint8Array.from(atob(input.base64),character=>character.charCodeAt(0));}catch{throw new SopError('INVALID_SOP_EXCEL','Generated SOP workbook is invalid.',400);}if(bytes.length<100||bytes.length>20*1024*1024)throw new SopError('INVALID_SOP_EXCEL','Generated SOP workbook must be between 100 bytes and 20 MiB.',400);const token=await attachments.upload({appToken:config.appToken,fileName,bytes,mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),stamp=now().getTime(),fields={[F.excel]:[{file_token:token}],[F.updatedAt]:stamp,[F.updatedBy]:text(input.updatedBy).trim()};const saved=await records.updateRecord({...args(),recordId:record.record_id,fields}),complete={...record,...saved,fields:{...record.fields,...saved.fields}};return {...summary(complete),fileName,excelStored:true};}
 async function remove(sopId){const record=await find(sopId);await records.deleteRecord({...args(),recordId:record.record_id});return {sopId,deleted:true,assetsRetained:true};}
 async function asset(sopId,assetId){const record=await find(sopId),data=parse(record),stored=attachmentMap(record);let found;for(const page of data.pages)for(const key of ['image1','image2','image3'])if(page.zone3?.[key]?.assetId===assetId)found=page.zone3[key];const token=text(found?.fileToken)||stored.get(text(found?.fileName));if(!token)throw new SopError('SOP_ASSET_NOT_FOUND','SOP image was not found.',404);return attachments.download(token);}
 return {create,list,get,update,saveExcel,delete:remove,asset,allocate};
}
