const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const XLSX=require('../vendor/xlsx.full.min.js');
const columns=['UNIT ID','SN','TRACKING NUMBER','CLIENT ID','WAREHOUSE','REPAIR DATE','TIMES OF RE-ENTER','CURRENT STEP','ISSUE FOUND','PRE-QC NOTE','PART USED DETAIL','TOTAL PARTS USED','LABOR MINUTES','REPAIR LEVEL','REPAIR RESULT','FINAL QC RESULT','FINAL QC NOTE','CLIENT STATUS'];
const rows=Array.from({length:123},(_,i)=>Object.fromEntries(columns.map(k=>[k,k==='SN'?`<SN-${i}>`:k==='CURRENT STEP'?String(i%3+1):`${k}-${i}`])));
function setup(){const nodes=new Map(),calls=[];let workbook,filename;
 const node=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',value:'',querySelector:node,querySelectorAll:()=>[],reset(){},showModal(){this.open=true;},close(){this.open=false;}});return nodes.get(s);};
 const window={XLSX:{...XLSX,writeFile:(b,f)=>{workbook=b;filename=f;}},MkiteApiClient:{post:async(path,body)=>{calls.push({path,body});const page=body.page||1;return {ok:true,data:{columns,options:{},exportLimit:5000,results:body.export?rows:rows.slice((page-1)*50,page*50),summary:{found:123,pending:41,completed:41,disposal:41,totalLaborMinutes:1230},pagination:{page,totalPages:3,totalMatched:123,hasPrevious:page>1,hasNext:page<3}}};}}};
 vm.runInNewContext(fs.readFileSync('js/client-tools/tineco-toc/inventory.js','utf8'),{window});const module=window.MkiteClientToolModules['tineco.inventory'];module.init({root:node('root')});return {window,module,t:module._test,node,calls,get workbook(){return workbook;},get filename(){return filename;}};
}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
test('new registry tool is warehouse-aware and directory includes both distinct Tineco themes',()=>{const window={};vm.runInNewContext(fs.readFileSync('js/client-tools-registry.js','utf8'),{window});const tools=window.MkiteClientToolRegistry.filter({clientId:'TINECO-TOC'});assert.equal(tools.length,2);const t=tools.find(t=>t.toolId==='CT-MKS66-TINECO-TOC-0002');assert.equal(t.warehouse,'MKS66');assert.equal(t.route,'tineco-toc-batch-inventory');assert.equal(t.cardTheme,'indigo');assert.equal(tools[0].cardTheme,'teal');assert.ok(fs.readFileSync('index.html','utf8').includes('js/client-tools/tineco-toc/inventory.js'));});
test('auto-load, table, server pagination, detail escaping, and clear reload',async()=>{const h=setup();assert.match(h.node('#tci-message').textContent,/Loading/);await flush();assert.equal(JSON.stringify(h.calls[0].body),JSON.stringify({page:1}));assert.match(h.node('#tci-results').innerHTML,/Showing 1–50 of 123/);assert.match(h.node('#tci-results').innerHTML,/EXPORT FILTERED RESULTS/);assert.match(h.node('#tci-results').innerHTML,/&lt;SN-0&gt;/);h.t.detail(0);assert.match(h.node('#tci-detail').innerHTML,/1 — Pre-QC/);assert.match(h.node('#tci-detail').innerHTML,/&lt;SN-0&gt;/);h.t.detail(1);assert.match(h.node('#tci-detail').innerHTML,/2 — Repair/);h.t.detail(2);assert.match(h.node('#tci-detail').innerHTML,/3 — Final QC/);await h.t.search({sn:'abc'},3);assert.match(h.node('#tci-results').innerHTML,/Showing 101–123 of 123/);h.node('[name="sn"]').value='abc';h.node('#tci-clear').onclick();await flush();assert.equal(h.node('[name="sn"]').value,'');assert.equal(h.calls.at(-1).body.page,1);assert.equal(h.calls.at(-1).body.sn,undefined);h.module.cleanup();});
test('filtered export retrieves every matching page and expected columns with dated filename',async()=>{const h=setup();await flush();await h.t.search({clientStatus:'Pending'});await h.t.exportFiltered();assert.equal(h.calls.at(-1).body.export,true);assert.equal(h.calls.at(-1).body.clientStatus,'Pending');const sheet=h.workbook.Sheets['TINECO Inventory'],exported=XLSX.utils.sheet_to_json(sheet);assert.equal(exported.length,123);assert.deepEqual(Object.keys(exported[0]),columns);assert.match(h.filename,/^TINECO_TOC_BATCH_INVENTORY_\d{4}-\d{2}-\d{2}\.xlsx$/);assert.equal(sheet.B2.t,'s');assert.equal(sheet.B2.f,undefined);h.module.cleanup();});
test('export limit and incomplete responses show errors without producing partial workbooks',async()=>{for(const incomplete of [true,false]){const h=setup();await flush();h.window.MkiteApiClient.post=async()=>incomplete?{ok:true,data:{columns,results:rows.slice(0,50),pagination:{totalMatched:123}}}:{ok:false,error:{message:'Export is limited to 5000 filtered records.'}};await h.t.exportFiltered();assert.equal(h.workbook,undefined);assert.match(h.node('#tci-message').textContent,incomplete?/Incomplete/:/limited to 5000/);h.module.cleanup();}});
test('empty and failed searches provide clear operational messages',async()=>{const h=setup();await flush();const html=h.t.resultHtml({results:[],exportLimit:5000,summary:{found:0,pending:0,completed:0,disposal:0,totalLaborMinutes:0},pagination:{page:1,totalPages:1,totalMatched:0}});assert.match(html,/NO TINECO TOC UNITS FOUND/);h.window.MkiteApiClient.post=async()=>{throw Error('offline');};await h.t.search({});assert.match(h.node('#tci-message').textContent,/Unable to load TINECO TOC inventory/);h.module.cleanup();});

for(const [page,totalPages] of [[1,3],[3,3],[1,1]])test(`compact toolbar page ${page}/${totalPages} preserves disabled states and labels`,()=>{
 const h=setup(),html=h.t.resultHtml({results:rows.slice(0,8),exportLimit:5000,summary:{found:8,pending:8,completed:0,disposal:0,totalLaborMinutes:80},pagination:{page,totalPages,totalMatched:8,hasPrevious:page>1,hasNext:page<totalPages}});
 assert.match(html,/class="tci-result-toolbar"/);assert.match(html,/class="button tci-utility tci-export"/);assert.match(html,/aria-describedby="tci-export-help"/);
 assert.match(html,/All matching pages · maximum 5000 records/);assert.ok(html.includes(`Page ${page} of ${totalPages}`));
 assert.match(html,/← PREVIOUS/);assert.match(html,/NEXT →/);
 for(const [id,disabled] of [['previous',page===1],['next',page===totalPages]])assert.equal(/\bdisabled\b/.test(html.match(new RegExp(`<button[^>]*id="tci-${id}"[^>]*>`))[0]),disabled);
 h.module.cleanup();
});
test('toolbar click pagination and export retain active filters and all-result export',async()=>{
 const h=setup();await flush();await h.t.search({sn:'ABC'});
 const click=id=>h.node('#tci-results').onclick({target:{closest:s=>s===`#tci-${id}`?{}:null}});
 await click('next');assert.equal(h.calls.at(-1).body.page,2);assert.equal(h.calls.at(-1).body.sn,'ABC');
 await click('previous');assert.equal(h.calls.at(-1).body.page,1);
 const count=h.calls.length;await click('previous');assert.equal(h.calls.length,count);
 await click('export');assert.equal(h.calls.at(-1).body.export,true);assert.equal(h.calls.at(-1).body.sn,'ABC');assert.equal(XLSX.utils.sheet_to_json(h.workbook.Sheets['TINECO Inventory']).length,123);h.module.cleanup();
});
test('toolbar utility sizing and responsive wrapping are scoped to results',()=>{
 const css=fs.readFileSync('css/client-tools/tineco-inventory.css','utf8');assert.match(css,/\.tci-app \.tci-result-toolbar \.tci-utility \{ min-height:38px/);assert.match(css,/\.tci-pagination \{[^}]*flex-wrap:wrap/);assert.match(css,/@media\(max-width:600px\)\s*\{\s*\.tci-result-toolbar \{ grid-template-columns:minmax\(0,1fr\)/);
});
