import { IDENTITY, TEXT_FIELDS, NUMBER_FIELDS, FORM_FIELDS, fail } from './tineco-fields.js';
const text=v=>Array.isArray(v)?v.map(x=>x.text||'').join(''):String(v??'').trim();
const rawText=v=>Array.isArray(v)?v.map(x=>x.text||'').join(''):String(v??'');
const norm=v=>text(v).toUpperCase();
const outcomes=[['NFF','Awaiting Parts'],['Can Not Be Fixed'],['Completed','Final QC Fail','Client Confirmed Disposal']];
const mapping={trackingNumber:'TRACKING NUMBER',issueFound:'ISSUE FOUND',preQcNote:'PRE-QC NOTE',partUsedDetail:'PART USED DETAIL',totalPartsUsed:'TOTAL PARTS USED',repairLevel:'REPAIR LEVEL',finalQcNote:'FINAL QC NOTE'};
export function createTinecoService(config,records,storage,{now=()=>Date.now()}={}) {
 const args=()=>{if(!config.tinecoTocUnitTableId)fail('TINECO_TOC_TABLE_NOT_CONFIGURED','Configure the Tineco unit table.',503);return {appToken:config.appToken,tableId:config.tinecoTocUnitTableId};};
 const key=input=>{if(!/^[a-zA-Z0-9-]{16,80}$/.test(input?.requestId||''))fail('SESSION_ID_REQUIRED','A valid repair session identity is required.',400);return `visit:${input.requestId}`;};
 const save=job=>storage.put(key(job),job);
 const reservation=sn=>`sn:${norm(sn)}`;
 const list=()=>records.listRecords(args());
 function unique(rows,sn){const matches=rows.filter(r=>norm(r.fields?.SN)===norm(sn));if(matches.length>1)fail('DUPLICATE_SN_RECORDS',`Found ${matches.length} records for this SN. Resolve duplicates before continuing.`);return matches[0];}
 async function schema(){const f=new Map((await records.listFields(args())).map(x=>[x.field_name,x]));const numeric=[...NUMBER_FIELDS,'CURRENT STEP'];const required=[...TEXT_FIELDS,...numeric,'REPAIR DATE','WAREHOUSE','REPAIR LEVEL','REPAIR RESULT','FINAL QC RESULT','CLIENT STATUS'];const bad=required.filter(k=>!f.has(k)||(TEXT_FIELDS.includes(k)?f.get(k).type!==1:numeric.includes(k)?f.get(k).type!==2:k==='REPAIR DATE'?f.get(k).type!==5:k==='CLIENT STATUS'?f.get(k).type!==3:![1,3].includes(f.get(k).type)));if(bad.length)fail('TINECO_TOC_SCHEMA_INVALID',`Missing or incompatible fields: ${bad.join(', ')}.`,400);return f;}
 function option(f,k,v,code='TINECO_TOC_SCHEMA_INVALID'){if(f.get(k)?.type===3&&!f.get(k).property?.options?.some(o=>o.name===v))fail(code,`Configure ${k} option: ${v}.`,400);}
 function form(input){const data=Object.fromEntries(FORM_FIELDS.map(k=>[k,text(input?.[k])]));if(Object.values(data).some(v=>v.length>10000))fail('INVALID_FORM','A repair field is too long.',400);const parts=data.partUsedDetail.split(/\r?\n/).map(text).filter(Boolean);data.partUsedDetail=parts.join('\n');data.totalPartsUsed=String(parts.length);return data;}
 function issue(data){if(!data.issueFound)fail('ISSUE_FOUND_REQUIRED','ISSUE FOUND is required.',400);}
 function repair(data){if(!data.repairLevel)fail('REPAIR_LEVEL_REQUIRED','Choose a repair level.',400);}
 function number(v,label){const n=Number(v||0);if(!Number.isSafeInteger(n)||n<0)fail('TINECO_TOC_RECORD_INVALID',`Invalid ${label}.`);return n;}
 function identity(record,job){const f=record?.fields||{};if(!record?.record_id||(job.recordId&&record.record_id!==job.recordId)||norm(f.SN)!==norm(job.sn)||text(f['CLIENT ID'])!==IDENTITY.clientId||text(f.WAREHOUSE)!==IDENTITY.warehouse||text(f['UNIT ID'])!==job.unitId)fail('UNIT_RECORD_CONFLICT','Unit record identity or ownership changed.');return f;}
 const view=j=>({requestId:j.requestId,recordId:j.recordId,unitId:j.unitId,sn:j.sn,entry:j.entry,timesOfReEnter:j.entry,startedAt:j.startedAt,step:j.step,currentStep:j.step+1,phase:j.phase,clientStatus:j.clientStatus,previousLaborMinutes:j.previousLaborMinutes,resumed:j.resumed,repairResult:j.repairResult,finalQcResult:j.finalQcResult,generalNote:j.generalNote||'',data:j.data,repairLevels:j.repairLevels,result:j.result,...IDENTITY});
 async function load(input){const j=await storage.get(key(input));if(!j)fail('SESSION_NOT_FOUND','Repair session was not found.');if(j.model!==2)fail('SESSION_MODEL_CHANGED','This draft uses the old visit model. Resolve it before starting a new entry.');return j;}
 const same=(fields,patch)=>Object.entries(patch).every(([k,v])=>text(fields?.[k])===text(v));
 async function current(j){return records.getRecord({...args(),recordId:j.recordId});}
 async function owned(j){if(await storage.get(reservation(j.sn))!==j.requestId)fail('UNIT_ALREADY_ACTIVE','This unit belongs to another active entry.');const record=await current(j),f=identity(record,j);if(f['CLIENT STATUS']!=='Pending'||number(f['TIMES OF RE-ENTER'],'re-entry')!==j.entry||number(f['LABOR MINUTES'],'labor')!==j.previousLaborMinutes||Number(f['CURRENT STEP'])!==j.step+1)fail('UNIT_RECORD_CONFLICT','Unit state changed outside this entry.');return record;}
 // Every external mutation has a durable absolute-value patch. Retry either confirms
 // that patch or retries it against an unchanged preimage; it never increments again.
 async function apply(j,fresh=false){const m=j.mutation;let record;
   if(m.create){record=unique(await list(),j.sn);if(!record&&fresh){await records.createRecord({...args(),fields:m.patch});record=unique(await list(),j.sn);}if(!record)fail('TINECO_TOC_SAVE_UNCONFIRMED','Creation is unconfirmed. Retry this entry; do not create another unit.');}
   else {record=await current(j);identity(record,j);if(!same(record.fields,m.patch)){if(!same(record.fields,m.before))fail('UNIT_RECORD_CONFLICT','Unit changed while an update was pending.');await records.updateRecord({...args(),recordId:j.recordId,fields:m.patch});record=await current(j);}}
   identity(record,j);if(!same(record.fields,m.patch))fail('TINECO_TOC_SAVE_UNCONFIRMED','Unit update was not confirmed. Retry the same entry.');
   j.recordId=record.record_id;Object.assign(j,m.after);j.lastMutation={action:m.action,signature:m.signature};delete j.mutation;j.phase=m.action==='finish'?'saved':m.action==='pause'?'paused':'draft';await save(j);return view(j);
 }
 async function mutate(j,action,signature,patch,after,before,create=false){j.mutation={action,signature,patch,after,before,create};await save(j);return apply(j,true);}
 function dataPatch(data){return Object.fromEntries(Object.entries(mapping).map(([k,f])=>[f,k==='totalPartsUsed'?Number(data[k]):k==='repairLevel'&&!data[k]?null:data[k]]));}
 function timestamp(value){const p=new Intl.DateTimeFormat('en-CA',{timeZone:config.warehouseTimeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const get=k=>p.find(v=>v.type===k).value;return `${get('year')}/${get('month')}/${get('day')} ${get('hour')}:${get('minute')}`;}
 return {
 async begin(input){const id=key(input),sn=text(input.sn);if(!sn)fail('SN_REQUIRED','Scan or enter the serial number.',400);if(sn.length>500)fail('SN_INVALID','Serial number is too long.',400);
   const old=await storage.get(id);if(old){if(old.model!==2)fail('SESSION_MODEL_CHANGED','This entry belongs to the old visit model. Resolve the old draft first.');if(norm(old.sn)!==norm(sn))fail('DUPLICATE_SAVE_PREVENTED','This entry belongs to another SN.');return old.mutation?apply(old):view(old);}
   const fields=await schema(),rows=await list(),record=unique(rows,sn),f=record?.fields||{};
   const j={model:2,requestId:input.requestId,sn:record?text(f.SN):sn,recordId:record?.record_id,unitId:text(f['UNIT ID']),entry:record?number(f['TIMES OF RE-ENTER'],'re-entry'):0,step:record?Number(f['CURRENT STEP'])-1:0,clientStatus:record?text(f['CLIENT STATUS']):'Pending',previousLaborMinutes:number(f['LABOR MINUTES'],'labor'),generalNote:text(f['GENERAL NOTE']),data:form(Object.fromEntries(Object.entries(mapping).map(([k,v])=>[k,f[v]]))),repairLevels:fields.get('REPAIR LEVEL').property?.options?.map(o=>o.name)||[],resumed:!!record,repairResult:text(f['REPAIR RESULT']),finalQcResult:text(f['FINAL QC RESULT']),phase:'draft'};
   if(record){identity(record,j);if(!j.unitId)fail('TINECO_TOC_RECORD_INVALID','Existing unit has no Unit ID.');if(['Completed','Disposal'].includes(j.clientStatus)){j.phase=j.clientStatus==='Completed'?'completed':'disposal';j.result={sn:j.sn,unitId:j.unitId,repairResult:text(f['REPAIR RESULT']),laborMinutes:j.previousLaborMinutes,entry:j.entry};await save(j);return view(j);}if(j.clientStatus!=='Pending'||![0,1,2].includes(j.step))fail('TINECO_TOC_RECORD_INVALID','Pending units require CURRENT STEP 1, 2 or 3.');}
   const owner=await storage.get(reservation(sn));if(owner){const active=await storage.get(`visit:${owner}`);if(active&&!['saved','paused','cancelled','completed','disposal'].includes(active.phase))fail('UNIT_ALREADY_ACTIVE','This SN already has an active entry. Resume or cancel that entry first.');}
   option(fields,'CLIENT STATUS','Pending');option(fields,'WAREHOUSE',IDENTITY.warehouse);
   if(!record){const day=timestamp(now()).slice(0,10).replaceAll('/',''),prefix=`TCU-${day}-`;let seq=Number(await storage.get(`sequence:${day}`))||0;for(const r of rows){const v=text(r.fields?.['UNIT ID']);if(v.startsWith(prefix)&&/^\d{4,}$/.test(v.slice(prefix.length))&&Number.isSafeInteger(Number(v.slice(prefix.length))))seq=Math.max(seq,Number(v.slice(prefix.length)));}j.unitId=prefix+String(seq+1).padStart(4,'0');await storage.put(`sequence:${day}`,seq+1);}
   j.entry++;j.startedAt=now();await storage.put(reservation(sn),j.requestId);
   const patch=record?{'TIMES OF RE-ENTER':j.entry,'REPAIR DATE':j.startedAt}:{'UNIT ID':j.unitId,SN:j.sn,'CLIENT ID':IDENTITY.clientId,WAREHOUSE:IDENTITY.warehouse,'CLIENT STATUS':'Pending','CURRENT STEP':1,'TIMES OF RE-ENTER':1,'LABOR MINUTES':0,'PART USED DETAIL':'','TOTAL PARTS USED':0,'REPAIR DATE':j.startedAt};
   return mutate(j,'begin','begin',patch,{},record?{'TIMES OF RE-ENTER':f['TIMES OF RE-ENTER'],'CLIENT STATUS':'Pending','LABOR MINUTES':f['LABOR MINUTES'],'CURRENT STEP':f['CURRENT STEP']}:null,!record);
 },
 async step(input){const j=await load(input),data=form(input.data),signature=JSON.stringify({from:input.from,to:input.to,data});if(j.mutation){if(j.mutation.action!=='step'||j.mutation.signature!==signature)fail('DUPLICATE_SAVE_PREVENTED','Retry the original pending operation.');return apply(j);}if(j.phase!=='draft')fail('SESSION_NOT_EDITABLE','This entry is no longer editable.');if(j.lastMutation?.action==='step'&&j.lastMutation.signature===signature)return view(j);
   if(j.step!==input.from||![0,1,2].includes(input.to)||Math.abs(input.to-input.from)!==1)fail('INVALID_STAGE_TRANSITION','Move through steps in order.');if(input.to>j.step){if(j.step===0)issue(data);if(j.step===1)repair(data);}
   const fields=await schema();if(data.repairLevel)option(fields,'REPAIR LEVEL',data.repairLevel,'REPAIR_LEVEL_OPTION_NOT_AVAILABLE');const record=await owned(j),patch={...dataPatch(data),'CURRENT STEP':input.to+1,'REPAIR DATE':now()};return mutate(j,'step',signature,patch,{step:input.to,data},record.fields);
 },
 async cancel(input){const j=await load(input);if(j.phase==='cancelled')return view(j);if(j.phase!=='draft'||j.mutation)fail('SESSION_NOT_EDITABLE','Resolve pending operations before cancelling.');j.phase='cancelled';await save(j);return view(j);},
 async pause(input){const j=await load(input),data=form(input.data),pauseNote=text(input.pauseNote),signature=JSON.stringify({pauseNote,data});if(!pauseNote)fail('PAUSE_NOTE_REQUIRED','PAUSE NOTE is required.',400);if(pauseNote.length>10000)fail('INVALID_FORM','Pause Note is too long.',400);if(j.mutation){if(j.mutation.action!=='pause'||j.mutation.signature!==signature)fail('DUPLICATE_SAVE_PREVENTED','Retry the original pending pause.');return apply(j);}if(j.phase==='paused'){if(j.lastMutation?.signature!==signature)fail('DUPLICATE_SAVE_PREVENTED','This entry is already paused.');return view(j);}if(j.phase!=='draft')fail('SESSION_NOT_EDITABLE','This entry is no longer editable.');
   const fields=await schema();if(data.repairLevel)option(fields,'REPAIR LEVEL',data.repairLevel,'REPAIR_LEVEL_OPTION_NOT_AVAILABLE');const record=await owned(j),endedAt=now(),sessionLabor=Math.max(1,Math.ceil((endedAt-j.startedAt)/60000)),labor=j.previousLaborMinutes+sessionLabor;
   const line=`${timestamp(endedAt)} PAUSED - NOTE: ${pauseNote}`;const existingGeneralNote=rawText(record.fields['GENERAL NOTE']);const generalNote=existingGeneralNote?`${existingGeneralNote}\n${line}`:line;const patch={...dataPatch(data),'GENERAL NOTE':generalNote,'CLIENT STATUS':'Pending','CURRENT STEP':j.step+1,'LABOR MINUTES':labor,'REPAIR DATE':endedAt};
   return mutate(j,'pause',signature,patch,{data,generalNote,clientStatus:'Pending',result:{sn:j.sn,unitId:j.unitId,laborMinutes:labor,sessionLaborMinutes:sessionLabor,entry:j.entry,pauseNote,resumeStep:j.step}},record.fields);
 },
 async finish(input){const j=await load(input),data=form(input.data),signature=JSON.stringify({outcome:input.outcome,data});if(j.mutation){if(j.mutation.action!=='finish'||j.mutation.signature!==signature)fail('DUPLICATE_SAVE_PREVENTED','Retry the original pending save.');return apply(j);}if(j.phase==='saved'){if(j.lastMutation.signature!==signature)fail('DUPLICATE_SAVE_PREVENTED','This entry is already saved.');return view(j);}if(j.phase!=='draft'||!outcomes[j.step].includes(input.outcome))fail('INVALID_STAGE_TRANSITION','Outcome is unavailable in this step.');if(j.step===0)issue(data);if(j.step>0)repair(data);if(input.outcome==='Final QC Fail'&&!data.finalQcNote)fail('FINAL_QC_FAILURE_REASON_REQUIRED','FINAL QC FAILURE REASON REQUIRED',400);
   const disposal=input.outcome==='Client Confirmed Disposal';
   if(disposal&&!data.finalQcNote)fail('DISPOSAL_NOTE_REQUIRED','Write the client-confirmed disposal details in FINAL QC NOTE.',400);
   const result=disposal?'Scrap':input.outcome;
   const fields=await schema(),status=disposal?'Disposal':input.outcome==='Completed'?'Completed':'Pending',final=j.step===2&&!disposal?(status==='Completed'?'Pass':'Fail'):null;option(fields,'CLIENT STATUS',status);option(fields,'REPAIR RESULT',result,'REPAIR_RESULT_OPTION_NOT_AVAILABLE');if(final)option(fields,'FINAL QC RESULT',final,'FINAL_QC_RESULT_OPTION_NOT_AVAILABLE');if(data.repairLevel)option(fields,'REPAIR LEVEL',data.repairLevel,'REPAIR_LEVEL_OPTION_NOT_AVAILABLE');
   const record=await owned(j),endedAt=now(),sessionLabor=Math.max(1,Math.ceil((endedAt-j.startedAt)/60000)),labor=j.previousLaborMinutes+sessionLabor;
   const patch={...dataPatch(data),'REPAIR RESULT':result,'FINAL QC RESULT':final,'FINAL QC NOTE':j.step===2?data.finalQcNote:'','CLIENT STATUS':status,'CURRENT STEP':j.step+1,'LABOR MINUTES':labor,'REPAIR DATE':endedAt};if(fields.get('NOTE')?.type===1){const line=`${timestamp(endedAt)} - ENTRY #${j.entry} - STEP ${j.step+1} - ${input.outcome.toUpperCase()} - SESSION LABOR ${sessionLabor} MIN`;patch.NOTE=[text(record.fields.NOTE),line].filter(Boolean).join('\n');}
   return mutate(j,'finish',signature,patch,{data,clientStatus:status,repairResult:result,finalQcResult:final||'',result:{sn:j.sn,unitId:j.unitId,repairResult:result,laborMinutes:labor,sessionLaborMinutes:sessionLabor,entry:j.entry}},record.fields);
 }
 };
}
