import test from 'node:test';
import assert from 'node:assert/strict';
import { createSafetyIconService } from '../src/modules/safety-icons/safety-icon-service.js';

const field=(field_name,type)=>({field_name,type});
const fields=[field('SAFETY ICON NOTE',1),field('SAFETY ICON IMAGE',17),field('SAFETY ICON FUCNTION',1),field('SAFETY ICON ID',1),field('STATUS',1),field('SORT ORDER',1)];
function fixture({configured=true}={}){
 const rows=[{record_id:'rec2',fields:{'SAFETY ICON ID':'SIC-0002','SAFETY ICON NOTE':'当心触电','SAFETY ICON FUCNTION':'激光焊接',STATUS:'Inactive','SORT ORDER':'20','SAFETY ICON IMAGE':[{file_token:'PRIVATE-TOKEN',name:'electric.png',type:'image/png',size:25,url:'private'}]}},{record_id:'rec1',fields:{'SAFETY ICON ID':'SIC-0001','SAFETY ICON NOTE':'注意安全','SAFETY ICON FUCNTION':'捆扎',STATUS:'Active','SORT ORDER':'10','SAFETY ICON IMAGE':[{file_token:'PRIVATE-ONE',name:'safe.png',type:'image/png',size:20}]}}],writes=[],uploads=[];
 const records={listFields:async()=>structuredClone(fields),listRecords:async()=>structuredClone(rows),getRecord:async({recordId})=>structuredClone(rows.find(r=>r.record_id===recordId)||{}),createRecord:async({fields})=>{writes.push(structuredClone(fields));const row={record_id:'rec3',fields:structuredClone(fields)};rows.push(row);return structuredClone(row);},updateRecord:async({recordId,fields})=>{writes.push(structuredClone(fields));Object.assign(rows.find(r=>r.record_id===recordId).fields,structuredClone(fields));return structuredClone(rows.find(r=>r.record_id===recordId));}};
 const attachments={upload:async input=>{uploads.push(input);return 'NEW-PRIVATE-TOKEN';},download:async token=>{assert.match(token,/^PRIVATE/);return new Response('image',{headers:{'Content-Type':'image/png'}});}};
 return {rows,writes,uploads,records,attachments,service:createSafetyIconService({appToken:'base',safetyIconTableId:configured?'icons':''},records,attachments)};
}
const image={name:'new.png',type:'image/png',base64:'AQID'};
test('list maps actual typo field, attachment metadata and optional text fields without leaking tokens',async()=>{const f=fixture(),result=await f.service.list();assert.deepEqual(result.icons.map(i=>i.recordId),['rec1','rec2']);assert.deepEqual(result.icons[1],{recordId:'rec2',safetyIconId:'SIC-0002',note:'当心触电',function:'激光焊接',status:'Inactive',sortOrder:20,image:{name:'electric.png',mimeType:'image/png',size:25,url:'/api/safety-icons/image/rec2'}});assert.deepEqual(result.schema.supports,{safetyIconId:true,status:true,sortOrder:true});assert.deepEqual(result.schema.types,{id:1,note:1,image:17,function:1,status:1,sortOrder:1});assert.doesNotMatch(JSON.stringify(result),/PRIVATE|file_token|tmp_url/);});
test('create validates note/image, allocates collision-safe ID and writes attachment fields',async()=>{const f=fixture();await assert.rejects(f.service.create({note:'',image}),e=>e.code==='SAFETY_ICON_NOTE_REQUIRED');await assert.rejects(f.service.create({note:'New'}),e=>e.code==='SAFETY_ICON_IMAGE_REQUIRED');const saved=await f.service.create({note:' New ',function:' Work ',status:'Active',sortOrder:30,image});assert.equal(saved.safetyIconId,'SIC-0003');assert.deepEqual(f.writes[0],{'SAFETY ICON NOTE':'New','SAFETY ICON FUCNTION':'Work',STATUS:'Active','SORT ORDER':'30','SAFETY ICON ID':'SIC-0003','SAFETY ICON IMAGE':[{file_token:'NEW-PRIVATE-TOKEN'}]});assert.equal(f.uploads[0].mimeType,'image/png');});
test('create continues after the backfilled range with SIC-0013',async()=>{const f=fixture();for(let number=3;number<=12;number++)f.rows.push({record_id:`rec${number}`,fields:{'SAFETY ICON ID':`SIC-${String(number).padStart(4,'0')}`,'SAFETY ICON NOTE':`Icon ${number}`,'SAFETY ICON FUCNTION':'',STATUS:'Active','SORT ORDER':String(number)}});const saved=await f.service.create({note:'Next icon',function:'',status:'Active',sortOrder:13,image});assert.equal(saved.safetyIconId,'SIC-0013');assert.equal(f.writes[0]['SAFETY ICON ID'],'SIC-0013');});
test('edit updates text/status and preserves attachment when no replacement image is supplied',async()=>{const f=fixture();const saved=await f.service.update('rec1',{note:' Updated ',function:' New function ',status:'Inactive',sortOrder:11,image:null});assert.equal(saved.note,'Updated');assert.equal(saved.status,'Inactive');assert.equal(f.uploads.length,0);assert.equal(Object.hasOwn(f.writes[0],'SAFETY ICON IMAGE'),false);assert.equal(f.rows[1].fields['SAFETY ICON IMAGE'][0].file_token,'PRIVATE-ONE');});
test('image validation, missing configuration and download identity fail safely',async()=>{const f=fixture();for(const bad of [{name:'x.svg',type:'image/svg+xml',base64:'AQ=='},{name:'x.png',type:'image/png',base64:''}])await assert.rejects(f.service.create({note:'x',image:bad}),/image/i);await assert.rejects(fixture({configured:false}).service.list(),e=>e.code==='SAFETY_ICON_NOT_CONFIGURED'&&e.status===503);await assert.rejects(f.service.image('missing'),e=>e.code==='SAFETY_ICON_IMAGE_NOT_FOUND');assert.equal((await f.service.image('rec1')).headers.get('Content-Type'),'image/png');});
