import test from 'node:test';import assert from 'node:assert/strict';
import {createTinecoService} from '../src/modules/tineco-toc/tineco-service.js';
import {TEXT_FIELDS,NUMBER_FIELDS} from '../src/modules/tineco-toc/tineco-fields.js';
const requestId='visit-1234567890123456',nextId='visit-next-1234567890';
const form={trackingNumber:'TRACK/1',issueFound:'Motor issue',preQcNote:'Inspect',partUsedDetail:'Motor\nFilter',totalPartsUsed:'2',repairLevel:'Level 1',finalQcNote:'QC failure reason'};
const unit=(status='Pending',step=1)=>({record_id:'existing',fields:{SN:'ABC/123@T-_.#','UNIT ID':'TCU-20260901-0001','CLIENT ID':'TINECO-TOC',WAREHOUSE:'MKS66','CLIENT STATUS':status,'CURRENT STEP':step,'TIMES OF RE-ENTER':1,'LABOR MINUTES':15,'PART USED DETAIL':'Motor\nFilter','TOTAL PARTS USED':2,'REPAIR LEVEL':'Level 1','ISSUE FOUND':'Prior issue','PRE-QC NOTE':'Prior note','TRACKING NUMBER':'OLD','FINAL QC NOTE':'Previous failure','REPAIR RESULT':'Can Not Be Fixed','REPAIR DATE':1,NOTE:'old history'}});
function fixture(rows=[]){
 const data=structuredClone(rows),memory=new Map(),writes=[];let clock=Date.parse('2026-09-08T14:00:00Z');
 const fields=[...TEXT_FIELDS.map(field_name=>({field_name,type:1})),...[...NUMBER_FIELDS,'CURRENT STEP'].map(field_name=>({field_name,type:2})),{field_name:'REPAIR DATE',type:5},{field_name:'NOTE',type:1},...Object.entries({WAREHOUSE:['MKS66'],'CLIENT STATUS':['Pending','Completed','Disposal'],'REPAIR LEVEL':['Level 1','Level 2','Level 3'],'REPAIR RESULT':['Completed','NFF','Awaiting Parts','Can Not Be Fixed','Final QC Fail','Scrap'],'FINAL QC RESULT':['Pass','Fail']}).map(([field_name,options])=>({field_name,type:3,property:{options:options.map(name=>({name}))}}))];
 const records={listFields:async()=>fields,listRecords:async args=>{assert.equal(args.tableId,'tineco');return structuredClone(data);},getRecord:async({recordId})=>structuredClone(data.find(r=>r.record_id===recordId)),createRecord:async args=>{assert.equal(args.tableId,'tineco');const record={record_id:'created-'+data.length,fields:structuredClone(args.fields)};data.push(record);writes.push({type:'create',...args});return structuredClone(record);},updateRecord:async args=>{assert.equal(args.tableId,'tineco');Object.assign(data.find(r=>r.record_id===args.recordId).fields,structuredClone(args.fields));writes.push({type:'update',...args});return structuredClone(data.find(r=>r.record_id===args.recordId));}};
 const storage={get:async k=>structuredClone(memory.get(k)),put:async(k,v)=>memory.set(k,structuredClone(v))};const config={appToken:'base',tinecoTocUnitTableId:'tineco',warehouseTimeZone:'America/Toronto'};
 return {data,memory,writes,fields,records,storage,service:createTinecoService(config,records,storage,{now:()=>clock}),tick:(ms=61000)=>clock+=ms};
}
const begin=f=>f.service.begin({requestId,sn:' ABC/123@T-_.# '});
async function enter(f,step=0){await begin(f);for(let from=0;from<step;from++)await f.service.step({requestId,from,to:from+1,data:form});}
test('first SN creates one stable unit with numeric step, Pending and entry one',async()=>{const f=fixture();await assert.rejects(f.service.begin({requestId,sn:' '}),e=>e.code==='SN_REQUIRED');const j=await begin(f);assert.equal(j.sn,'ABC/123@T-_.#');assert.equal(j.recordId,'created-0');assert.equal(j.unitId,'TCU-20260908-0001');assert.equal(j.entry,1);assert.equal(j.currentStep,1);assert.equal(j.clientStatus,'Pending');await begin(f);assert.equal(f.data.length,1);assert.equal(f.writes.length,1);});
for(const step of [1,2,3])test(`Pending entry resumes step ${step} with prior data and increments once`,async()=>{const f=fixture([unit('Pending',step)]);const j=await begin(f);assert.equal(j.recordId,'existing');assert.equal(j.unitId,'TCU-20260901-0001');assert.equal(j.step,step-1);assert.equal(j.currentStep,step);assert.equal(j.entry,2);assert.equal(j.previousLaborMinutes,15);assert.equal(j.data.partUsedDetail,'Motor\nFilter');assert.equal(j.data.trackingNumber,'OLD');assert.equal(j.data.finalQcNote,'Previous failure');await begin(f);assert.equal(f.data.length,1);assert.equal(f.data[0].fields['TIMES OF RE-ENTER'],2);assert.equal(f.writes.length,1);});
for(const status of ['Completed','Disposal'])test(`${status} is lookup only without increment or reopening`,async()=>{const f=fixture([unit(status,3)]),before=structuredClone(f.data);const j=await begin(f);assert.equal(j.phase,status.toLowerCase());assert.equal(j.clientStatus,status);assert.equal(f.writes.length,0);assert.deepEqual(f.data,before);await assert.rejects(f.service.finish({requestId,outcome:'Completed',data:form}));});
test('duplicate exact normalized SN reports matching count without writes',async()=>{const f=fixture([unit(),{...unit(),record_id:'second',fields:{...unit().fields,SN:'abc/123@t-_.#'}}]);await assert.rejects(begin(f),e=>e.code==='DUPLICATE_SN_RECORDS'&&e.message.includes('2'));assert.equal(f.writes.length,0);});
test('Issue Found is mandatory before Pre-QC continue and both exits',async()=>{const f=fixture();await begin(f);for(const outcome of ['NFF','Awaiting Parts'])await assert.rejects(f.service.finish({requestId,outcome,data:{...form,issueFound:' '}}),e=>e.code==='ISSUE_FOUND_REQUIRED');await assert.rejects(f.service.step({requestId,from:0,to:1,data:{...form,issueFound:''}}),e=>e.code==='ISSUE_FOUND_REQUIRED');assert.equal(f.writes.length,1);});
for(const [outcome,step] of [['NFF',0],['Awaiting Parts',0],['Can Not Be Fixed',1],['Final QC Fail',2],['Completed',2]])test(`${outcome} updates same record with cumulative labor, disposition and numeric resume step`,async()=>{const f=fixture([unit('Pending',step+1)]);await begin(f);f.tick(8*60000);const input={requestId,outcome,data:form},saved=await f.service.finish(input),r=f.data[0].fields;assert.equal(f.data.length,1);assert.equal(r['UNIT ID'],'TCU-20260901-0001');assert.equal(r['LABOR MINUTES'],23);assert.equal(saved.result.laborMinutes,23);assert.equal(r['CURRENT STEP'],step+1);assert.equal(r['REPAIR RESULT'],outcome);assert.equal(r['CLIENT STATUS'],outcome==='Completed'?'Completed':'Pending');assert.equal(r['PART USED DETAIL'],'Motor\nFilter');assert.equal(r['TOTAL PARTS USED'],2);assert.ok(r['REPAIR DATE']>1);assert.equal(r['TRACKING NUMBER'],'TRACK/1');assert.match(r.NOTE,/old history\n.*ENTRY #2/);const before=structuredClone(f.data),count=f.writes.length;await f.service.finish(input);assert.equal(f.writes.length,count);assert.deepEqual(f.data,before);});
test('new same-SN entry reuses record/Unit ID and previous cumulative labor',async()=>{const f=fixture();await enter(f,1);f.tick();await f.service.finish({requestId,outcome:'Can Not Be Fixed',data:form});const j=await f.service.begin({requestId:nextId,sn:'ABC/123@T-_.#'});assert.equal(j.entry,2);assert.equal(j.step,1);assert.equal(j.previousLaborMinutes,2);assert.equal(f.data.length,1);assert.equal(j.unitId,f.data[0].fields['UNIT ID']);});
test('actual parts add/remove replaces list, server recalculates total',async()=>{const f=fixture([unit('Pending',2)]);await begin(f);await f.service.finish({requestId,outcome:'Can Not Be Fixed',data:{...form,partUsedDetail:'Motor\nFilter\nBrush',totalPartsUsed:'999'}});assert.equal(f.data[0].fields['TOTAL PARTS USED'],3);await f.service.begin({requestId:nextId,sn:'ABC/123@T-_.#'});await f.service.finish({requestId:nextId,outcome:'Can Not Be Fixed',data:{...form,partUsedDetail:'Filter\nBrush'}});assert.equal(f.data[0].fields['PART USED DETAIL'],'Filter\nBrush');assert.equal(f.data[0].fields['TOTAL PARTS USED'],2);assert.equal(f.data.length,1);});
test('continue persists step 2 then 3, backward edits persist and no forward skip',async()=>{const f=fixture();await begin(f);await assert.rejects(f.service.step({requestId,from:0,to:2,data:form}));for(let from=0;from<2;from++){const input={requestId,from,to:from+1,data:form};await f.service.step(input);await f.service.step(input);assert.equal(f.data[0].fields['CURRENT STEP'],from+2);}await f.service.step({requestId,from:2,to:1,data:form});assert.equal(f.data[0].fields['CURRENT STEP'],2);});
test('Final QC failure reason and repair level remain required',async()=>{const f=fixture([unit('Pending',3)]);await begin(f);await assert.rejects(f.service.finish({requestId,outcome:'Final QC Fail',data:{...form,finalQcNote:''}}),e=>e.code==='FINAL_QC_FAILURE_REASON_REQUIRED');await assert.rejects(f.service.finish({requestId,outcome:'Completed',data:{...form,repairLevel:''}}),e=>e.code==='REPAIR_LEVEL_REQUIRED');});
test('lost begin update acknowledgement increments once on retry',async()=>{const f=fixture([unit()]),update=f.records.updateRecord;f.records.updateRecord=async args=>{await update(args);throw Error('lost');};await assert.rejects(begin(f));const j=await begin(f);assert.equal(j.entry,2);assert.equal(f.writes.length,1);});
test('lost first create acknowledgement recovers same SN without duplicate',async()=>{const f=fixture(),create=f.records.createRecord;f.records.createRecord=async args=>{await create(args);throw Error('lost');};await assert.rejects(begin(f));await begin(f);assert.equal(f.data.length,1);assert.equal(f.writes.length,1);});
test('unconfirmed create never blindly creates again',async()=>{const f=fixture();let calls=0;f.records.createRecord=async()=>{calls++;throw Error('network');};await assert.rejects(begin(f));await assert.rejects(begin(f),e=>e.code==='TINECO_TOC_SAVE_UNCONFIRMED');assert.equal(calls,1);});
test('save recovery updates by authoritative ID only without duplicate labor or NOTE',async()=>{const f=fixture([unit('Pending',2)]);await begin(f);f.records.listRecords=async()=>{throw Error('final save must use recordId');};const update=f.records.updateRecord;f.records.updateRecord=async args=>{await update(args);throw Error('lost');};const input={requestId,outcome:'Can Not Be Fixed',data:form};await assert.rejects(f.service.finish(input));const before=structuredClone(f.data);await f.service.finish(input);assert.deepEqual(f.data,before);assert.equal(f.data[0].fields['LABOR MINUTES'],16);assert.equal((f.data[0].fields.NOTE.match(/ENTRY #2/g)||[]).length,1);});
test('failed-before-write update safely retries absolute patch, not increments',async()=>{const f=fixture([unit()]),update=f.records.updateRecord;let once=true;f.records.updateRecord=async args=>{if(once){once=false;throw Error('network');}return update(args);};await assert.rejects(begin(f));await begin(f);assert.equal(f.data[0].fields['TIMES OF RE-ENTER'],2);});
test('record identity/state changes block update',async()=>{for(const field of ['SN','UNIT ID','CLIENT ID','WAREHOUSE','CLIENT STATUS']){const f=fixture([unit()]);await begin(f);f.data[0].fields[field]='other';await assert.rejects(f.service.finish({requestId,outcome:'NFF',data:form}),e=>e.code==='UNIT_RECORD_CONFLICT');assert.equal(f.writes.length,1);}});
test('active entry reservation blocks another request but cancel releases operational ownership',async()=>{const f=fixture();await begin(f);await assert.rejects(f.service.begin({requestId:nextId,sn:'ABC/123@T-_.#'}),e=>e.code==='UNIT_ALREADY_ACTIVE');const count=f.writes.length;await f.service.cancel({requestId});assert.equal(f.writes.length,count);await f.service.begin({requestId:nextId,sn:'ABC/123@T-_.#'});assert.equal(f.data.length,1);});
test('optional NOTE absence and optional tracking accepted; missing field/options fail clearly',async()=>{const f=fixture();f.fields.splice(f.fields.findIndex(v=>v.field_name==='NOTE'),1);await begin(f);await f.service.finish({requestId,outcome:'NFF',data:{...form,trackingNumber:''}});assert.equal(f.data[0].fields['TRACKING NUMBER'],'');assert.equal(f.data[0].fields.NOTE,undefined);const bad=fixture();bad.fields.splice(bad.fields.findIndex(v=>v.field_name==='CURRENT STEP'),1);await assert.rejects(begin(bad),e=>e.code==='TINECO_TOC_SCHEMA_INVALID');});
test('coordinator serializes duplicate saves',async()=>{const {TinecoTocCoordinator}=await import('../src/modules/tineco-toc/tineco-coordinator.js');const f=fixture();await begin(f);const c=new TinecoTocCoordinator({},{});c.handle=()=>f.service.finish({requestId,outcome:'NFF',data:form});await Promise.all([c.fetch({}),c.fetch({})]);assert.equal(f.data.length,1);assert.equal(f.data[0].fields['LABOR MINUTES'],1);});
test('missing result option fails before update and pending numeric step is mandatory',async()=>{const f=fixture([unit('Pending',2)]);await begin(f);f.fields.find(v=>v.field_name==='REPAIR RESULT').property.options=[];await assert.rejects(f.service.finish({requestId,outcome:'Can Not Be Fixed',data:form}),e=>e.code==='REPAIR_RESULT_OPTION_NOT_AVAILABLE');assert.equal(f.writes.length,1);const g=fixture([unit('Pending',4)]);await assert.rejects(begin(g),e=>e.code==='TINECO_TOC_RECORD_INVALID');assert.equal(g.writes.length,0);});
test('old visit-model jobs are never replayed as new record mutations',async()=>{const f=fixture();f.memory.set(`visit:${requestId}`,{requestId,sn:'ABC/123@T-_.#',phase:'draft'});await assert.rejects(begin(f),e=>e.code==='SESSION_MODEL_CHANGED');assert.equal(f.writes.length,0);});
test('Tineco endpoints retain POST and localhost CORS forwarding',async()=>{
 const {handleRequest}=await import('../src/index.js');const env={ALLOWED_ORIGINS:'http://localhost:5501',FEISHU_APP_ID:'app',FEISHU_APP_SECRET:'secret',FEISHU_BASE_APP_TOKEN:'base',FEISHU_PACKAGE_TABLE_ID:'packages',FEISHU_CLIENT_TABLE_ID:'clients',FEISHU_TINECO_TOC_UNIT_TABLE_ID:'tineco',TINECO_TOC:{idFromName:v=>v,get:()=>({fetch:async r=>{assert.equal((await r.json()).requestId,requestId);return Response.json({ok:true,data:{phase:'draft'}});}})}};
 for(const action of ['begin','step','finish','cancel']){const url=`https://api.example/api/tineco-toc/${action}`;assert.equal((await handleRequest(new Request(url),env)).status,405);const response=await handleRequest(new Request(url,{method:'POST',headers:{Origin:'http://localhost:5501','Content-Type':'application/json'},body:JSON.stringify({requestId})}),env);assert.equal(response.status,200);assert.equal(response.headers.get('Access-Control-Allow-Origin'),'http://localhost:5501');}
});

test('client-confirmed disposal resumes Repair, removes recovered parts and updates the same SN idempotently',async()=>{
 const f=fixture([unit('Pending',2)]),visit=await begin(f);
 assert.equal(visit.step,1);assert.equal(visit.data.partUsedDetail,'Motor\nFilter');
 const data={...visit.data,partUsedDetail:'Filter',finalQcNote:'Client confirmed disposal; motor recovered.'};
 await f.service.step({requestId,from:1,to:2,data});f.tick(8*60000);
 const update=f.records.updateRecord;let lost=true;
 f.records.updateRecord=async args=>{const r=await update(args);if(lost){lost=false;throw Error('lost response');}return r;};
 const input={requestId,outcome:'Client Confirmed Disposal',data};
 await assert.rejects(f.service.finish(input));const afterWrite=structuredClone(f.data);f.tick(600000);
 const saved=await f.service.finish(input);await f.service.finish(input);
 assert.deepEqual(f.data,afterWrite);assert.equal(f.data.length,1);assert.equal(f.data[0].record_id,'existing');
 const r=f.data[0].fields;assert.equal(r['UNIT ID'],visit.unitId);assert.equal(r['REPAIR RESULT'],'Scrap');assert.equal(r['CLIENT STATUS'],'Disposal');assert.equal(r['CURRENT STEP'],3);
 assert.equal(r['PART USED DETAIL'],'Filter');assert.equal(r['TOTAL PARTS USED'],1);assert.equal(r['FINAL QC NOTE'],data.finalQcNote);assert.equal(r['FINAL QC RESULT'],null);
 assert.equal(r['LABOR MINUTES'],23);assert.equal(r['TIMES OF RE-ENTER'],2);assert.equal(saved.result.repairResult,'Scrap');assert.equal(saved.phase,'saved');
 assert.equal((r.NOTE.match(/CLIENT CONFIRMED DISPOSAL/g)||[]).length,1);
 const count=f.writes.length;assert.equal((await f.service.begin({requestId:nextId,sn:visit.sn})).phase,'disposal');assert.equal(f.writes.length,count);
});
test('disposal is restricted to Final QC with a note and configured Scrap option',async()=>{
 for(const step of [1,2]){const f=fixture([unit('Pending',step)]);await begin(f);await assert.rejects(f.service.finish({requestId,outcome:'Client Confirmed Disposal',data:form}),e=>e.code==='INVALID_STAGE_TRANSITION');assert.equal(f.writes.length,1);}
 const f=fixture([unit('Pending',3)]);await begin(f);
 await assert.rejects(f.service.finish({requestId,outcome:'Client Confirmed Disposal',data:{...form,finalQcNote:' '}}),e=>e.code==='DISPOSAL_NOTE_REQUIRED');
 f.fields.find(x=>x.field_name==='REPAIR RESULT').property.options=f.fields.find(x=>x.field_name==='REPAIR RESULT').property.options.filter(x=>x.name!=='Scrap');
 await assert.rejects(f.service.finish({requestId,outcome:'Client Confirmed Disposal',data:form}),e=>e.code==='REPAIR_RESULT_OPTION_NOT_AVAILABLE');assert.equal(f.writes.length,1);
});
