import test from 'node:test'; import assert from 'node:assert/strict';
import { createToolRegistryService } from '../src/modules/tools/tool-registry-service.js';
function fixture(status=true) { const rows=[],writes=[]; const records={ listFields:async()=>['TOOL ID','TOOL NAME','WAREHOUSE','CLIENT ID','TOOL TYPE','ROUTE','DATA FIELDS',...(status?['STATUS']:[])].map(field_name=>({field_name})), listRecords:async()=>structuredClone(rows),createRecord:async({fields})=>{writes.push(fields);rows.push({record_id:'record'+rows.length,fields:{...fields,PRIVATE:'retained'}});}, updateRecord:async({recordId,fields})=>{writes.push(fields);Object.assign(rows.find(r=>r.record_id===recordId).fields,fields);} };return {rows,writes,records,service:createToolRegistryService({appToken:'base',toolTableId:'tools'},records)}; }
for(const status of [true,false]) test(`sync creates then retries without duplicates; optional STATUS ${status}`,async()=>{const f=fixture(status);assert.equal((await f.service.sync())[0].action,'created');assert.equal((await f.service.find('CT-MKS66-B044-0001')).fields.WAREHOUSE,'MKS66');await f.service.sync();assert.equal(f.writes.length,4);f.rows[0].fields['TOOL NAME']='Old';await f.service.sync();assert.deepEqual(f.writes[4],{'TOOL NAME':'Put Away Scan'});assert.equal(f.rows[0].fields.PRIVATE,'retained');assert.equal('STATUS' in f.rows[0].fields,status);});
test('duplicate upstream or registry IDs block sync and missing config is safe',async()=>{const f=fixture();await f.service.sync();f.rows.push(structuredClone(f.rows[0]));await assert.rejects(f.service.sync(),/DUPLICATE_TOOL_ID/);const s=createToolRegistryService({toolTableId:'tools'},f.records,{all:()=>[{toolId:'x'},{toolId:'x'}]});await assert.rejects(s.sync(),/DUPLICATE_TOOL_ID/);await assert.rejects(createToolRegistryService({},f.records).sync(),/NOT_CONFIGURED/);});
test('Tineco DATA FIELDS sync is idempotent and leaves B044 metadata untouched',async()=>{const f=fixture();await f.service.sync();const b044=structuredClone(f.rows[0]);const tineco=f.rows.find(r=>r.fields['TOOL ID']==='CT-MKS66-TINECO-TOC-0001');assert.equal(tineco.fields['TOOL NAME'],'TINECO TOC');assert.equal(JSON.parse(tineco.fields['DATA FIELDS'])[0].field,'SN');await f.service.sync();assert.equal(f.rows.length,4);assert.equal(f.writes.length,4);assert.deepEqual(f.rows[0],b044);});
test('Tineco inventory Tool ID sync creates once with read-only identity',async()=>{const f=fixture();await f.service.sync();await f.service.sync();const rows=f.rows.filter(r=>r.fields['TOOL ID']==='CT-MKS66-TINECO-TOC-0002');assert.equal(rows.length,1);assert.equal(rows[0].fields['TOOL NAME'],'TINECO TOC Batch Inventory');assert.equal(rows[0].fields.ROUTE,'tineco-toc-batch-inventory');assert.equal(rows[0].fields.WAREHOUSE,'MKS66');assert.equal(rows[0].fields['CLIENT ID'],'TINECO-TOC');assert.equal(rows[0].fields.STATUS,'Active');assert.equal(f.writes.length,4);});
test('Batch Picking List sync uses the existing In-House slug identity once and preserves client entries',async()=>{
 const f=fixture();await f.service.sync();await f.service.sync();const rows=f.rows.filter(r=>r.fields['TOOL ID']==='batch-picking-list');assert.equal(rows.length,1);
 assert.equal(rows[0].fields['TOOL TYPE'],'In-House Tool');assert.equal(rows[0].fields.ROUTE,'batch-picking-list');assert.equal(rows[0].fields.WAREHOUSE,'');assert.equal(rows[0].fields['CLIENT ID'],'');assert.equal(rows[0].fields.STATUS,'Active');assert.equal(f.writes.length,4);
});
